---

git_repo: git@github.com:yeti/whatbin.git
repo_name: wastesorting

project_name: wastesorting
application_name: wastesorting

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2etIf++q62fE3xdGFiy/xdiNrE3rpHDadLyAjmX9WGjHDKzW8xAh594Vr1yqTde1QqEl9J9WVN/fEVwC/qJlIufX+m0+i/VEO4MgMfuTmi9iVENoMqJqWH8HJIajkBOEMzps7FKAEw1CXPkmbkpy/Dm/U81k5mpaWXz2vYYHjDcihJXSPMVJVzWn604ckZSBgRBPrPe28UXMRoQkmvlrT2xcaDUgh2MkZzA+cKTxJGPRDv8KgkYJiwMoXMCEaRVlZCCM+N7M0bpAHQkAnSH07fyxnta37h56EKKuegXBR8bZ4HKP53S0HgTYCNp0p+OECmhOFESqCfx+WD85OTdvAMN7l6ODm8EOZB3rEvb46r3kUjQJsj3ni742Py2j0ouJY3L1/Jyst98BD666hiux5sT9tnI72VzP6yrf782pi2GGNYrkKFBo8pfg5syKE15ypvV3GgZbCoLbKC/es9HWqClP4zKnM3DkXUWwgJMaQN/lKw0yvKpNtx2ur/A9GI6BO4RQ95S+5vnZVUpvHX/xZNQRRprwaqt7AON30t3iaQpBnlQpIni1uPu93J8LskYPHYVMLwE0rmsDLLFDXWHstR/6MIvnqRBamNcF99oarroTrKfiO+lgrECgDKFBhN5ahbum/9sa0HapXMTKZRud/WI/j9165u8UxNbZ8oZlVOQ==
git_ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEAtnrSH/vqutnxN8XRhYsv8XYjaxN66Rw2nS8gI5l/Vhoxwys1
  vMQIefeFa9cqk3XtUKhJfSfVlTf3xFcAv6iZSLn1/ptPov1RDuDIDH7k5ovYlRDa
  DKialh/BySGo5AThDM6bOxSgBMNQlz5Jm5Kcvw5v1PNZOZqWll89r2GB4w3IoSV0
  jzFSVc1p+tOHJGUgYEQT6z3tvFFzEaEJJr5a09sXGg1IIdjJGcwPnCk8SRj0Q7/C
  oJGCYsDKFzAhGkVZWQgjPjezNG6QB0JAJ0h9O38sZ7Wt+4eehCirnoFwUfG2eByj
  +d0tB4E2AjadKfjhApoThREqgn8flg/OTk3bwDDe5ejg5vBDmQd6xL2+Oq95FI0C
  bI954u+Nj8to9KLiWNy9fycrLffAQ+uuoYrsebE/bZyO9lcz+sq3+/NqYthhjWK5
  ChQaPKX4ObMihNecqb1dxoGWwqC2ygv3rPR1qgpT+MypzNw5F1FsICTGkDf5SsNM
  ryqTbcdrq/wPRiOgTuEUPeUvub52VVKbx1/8WTUEUaa8GqrewDjd9Ld4mkKQZ5UK
  SJ4tbj7vdyfC7JGDx2FTC8BNK5rAyyxQ11h7LUf+jCL56kQWpjXBffaGq66E6yn4
  jvpYKxAoAyhQYTeWoW7pv/bGtB2qVzEymUbnf1iP4/deubvFMTW2fKGZVTkCAwEA
  AQKCAgBmnNhOHgYX/nhTiYzRkLxsBqfSDYk/Tpszdo2XFzjwvRggjMrSFFZD57mC
  M+OAOn8xrQBuPZkwKOHN6bLFE9TmfZPkEYgNum77c9FqnWywbBFlea10Etei9cau
  CJyFZGz9G61U4rs9EmveMKuJrT8xfLfMQu94ogJuGq6AUc+NU3HvlDVgVDbdgv5G
  iu5iu+8h0wZ0cUWfcRnI3wpbXA2NNpVeE/vs9I/ZTtO0V8fLvxmUg1+5lTmBuLGr
  qmfi8v5UP2w6D25ZXJbnTgzvSicJ7vCUfSiR2eh8nrYrEtSLb+XQ0yIuXn50yucJ
  BZcJRCebo/K4EDgcW8nyQ38ar1OTY1W7DqqgxazkYcdoF4RCaQiiuwdQSVQgUfz+
  WgwDHpneXZ1C3A7ongoQqjp3acqnSyBJ/O2503pIjC/ViVaJpTDY40UddcdGDoiT
  KvX3bK32fSh1XSobXl8OFb4wF0VuUfqY4jsmNxhgL2hkcC+40gQgvhGSLAxRls4q
  rMxmTAG3KvPg5i73zZRciwv3dY0BCyA7ozDBHpG8hYxuJgd0usvLhW1xC6atgoIB
  2t7UP0Z43AptE2izeVpJkyI0BkLv9t8ox7WSetk60Jsp9yWDTZXfo2uMeym4bkce
  zmfGOTUeSvENTKUvcZLGCgtzP4RYQZZLgXayG7SWdEDv6TtpBQKCAQEAzrxTRfw9
  ke9WgqaEfACHG9GeEtV1kW0k5uUSro8yuPeP8UDCJrKl9pOW5GM2D7f7O6wRpL7X
  KePXQmobo4C3hFU6HpP7huLUaOxu/UrHFNyVcLuOk0wB9Zfe8yNVMIfhTHDhdtDF
  rjA4pg6tPZMbayWlj0g8B09okwlMZwfFLG2gt3LS/eemyROSL+XRy/bAKoJ3JCXK
  SZE2ji6HCgtT98PT+GuBJ4L253pR5z9P8gys3tT3eRWb7i/9f0oNA0KhSod8OTHA
  8MOVEFPyRLXBPeEUC0PcPSZE0l/oVsF8YAE2Gi+WXkz33vEi4Qfucqj3OVZWaK1E
  Y+tLe5PsxB1URwKCAQEA4fbLCg0Z5mLOMdyC5TCsfUIdYGkj6wGqQZxIBSrbXlOy
  xWGaFh/uQfeF8DszxLZvWF5Qmh0HRAN0vavw4N9HAjNrcjpZjAYC+vy73mxhUabA
  SY6Ff43moLnQyPTeGdGjwzj6lbwSZZFlC1kWZjeKbvHmKmh96FIzYJRn4it8bwSz
  OpuFYhU/GY/mXZCo8M2jtcH/1K9xv7iP5xl2UNNZL1mMCd5NQLideEMtPAINLv07
  oI4XEmPsKN5HR1hOgETKvwr2fy9kbjPbzhbpZN2+LRV6Eb4KvVGM79oPmKe8u6nK
  OFBEojC6EMOHkYQfXTRiarAdj3S2zCNSKc+7BdBKfwKCAQBqI5ghU0qNFTL2KuXU
  ADVdm/YrNzqAKmgKv0sjIdPp0Pgu5Y+IbKn2eXm70g/cbBnpXgNE8NHo6NgIeg+s
  lxYhM9x9/H3jl6t0HwcwteaWGFYFJdYiW6CZ5ZoKfHZtTyXlqAKpjLAhKRK8dsaM
  2Wz3SsHAWVawbh2Dd/+o2f1qPPKJnMMkpn0juQ+R1c0riYjJimf+wAQmVw6KWurr
  xjsa9ohqf0806PE4kL1iG0hBPi62zOItYWHIHQ1p/6vEo73JVNv7RUcIlXF/i4nT
  qvkGevteeT2mi3JEDAduGzJu29BaC1qJGb0c0fKVVAwhBAzBfEkqvuJg5lm/nYeu
  fFxbAoIBAQC8IyVuWvYjkkSn0zfQ57PWHsQiz6euNZayRhLY6pP3d6yzFs6aeT+B
  ATwthr1VnagbZXuqtVylTlNW0OAf+wc+V92wH9EK+r5khyVMzeRBfZtAI0AXsehC
  DjQ9/VMnIBs/oiNRpGOU2XfN+QDjXn8OXK4MxS9/zWElmqrb7uUN8lXgCDkILzR4
  bg2Z/aYLyMvzu3Dsfp8wx9RY0CRoq2/oMqCcXtDngE7sINJ60iJz6zhIN8YR88xf
  QqMKTgYeWiiM4+3Ue3sdHmR2tTDiYJXFJ8qZFygN9OZplZ/CtHY5sebC+GIMwJFK
  /+HSULVkfwcqWTRjiwPf99CjK2hGMOS1AoIBAQC+HGbc1gD6cjsKcz/5hdfE4e4V
  ammaS61HOUTrZ3OSHXzmLPfWScm+smoN3jFpJ+0OAFZolbx/ub3Lj/c7xdyfi2uj
  +4CeQNSIYzShJqfxRvCCDIfz8CyxjRZGA5iuMrNgQvnkmg6ghN1RBbpLbv8HOXBI
  NpRplNYcPVt54sWIUHPBj8Zlsl5C/LxkIBtvfFc9/RyVowOVlZ/MogmyHrZ8zyxV
  d6UDhbjcdfFy67PXkHS2RN9VMcyxCtB4op9RCmwv/XSTICzWghAwHovDiMPGmYDf
  fMLjdid+/hOrr7NOnDpkV+efH8dGmzManEZPbEo3mpWVrX1UUsO+Tt0sExuH
  -----END RSA PRIVATE KEY-----

